version: "3.8"

services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: db
    volumes:
      - db-volume:/var/lib/mysql

  frontend:
    image: my-filesystem-portal:latest
    build:
      context: ./my-filesystem-portal
      args:
        - MYFILESYSTEM_BACKEND_HOST=0.0.0.0
    volumes:
      - frontend-dist:/app/dist

  frontend-dev:
    image: my-filesystem-portal-dev:latest
    profiles: [dev]
    build:
      dockerfile: dev.Dockerfile
      context: ./my-filesystem-portal
      args:
        - MYFILESYSTEM_BACKEND_HOST=0.0.0.0
    volumes:
      - ./my-filesystem-portal/src:/app/src
    ports:
      - 3000:3000

  server:
    hostname: server
    build:
      context: ./backend
      args:
        - JWT_SECRET=03cef2fd6d0b1ca7
        - BACKEND_DOMAIN=http://0.0.0.0:8080
        - DATABASE_URL=mysql://root:password@db:3306/db
    ports:
      - 8080:8080
    volumes:
      - frontend-dist:/app/frontend-dist

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

volumes:
  frontend-dist:
  db-volume:
